resilience4j:
    ratelimiter:
        configs:
            default:
                limitForPeriod: 15 
                limitRefreshPeriod: 3600s
                timeoutDuration: 0
        instances:
            apiRateLimit:
                baseConfig: default
